# Dockerfile

FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY logging_service logging_service

CMD ["python", "logging_service/main.py"]
